version: '3.5'

services:
  postgres_dev:
    container_name: postgres_dev
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres_data_dev:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres_network_dev
    restart: unless-stopped

networks:
  postgres_network_dev:
    driver: bridge

volumes:
  postgres_data_dev:
