version: '3.5'

services:
  postgres:
    container_name: postgres_prod
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres_data_prod:/data/postgres
    ports:
      - '5433:5432'
    networks:
      - postgres_network_prod
    restart: always

networks:
  postgres_network_prod:
    driver: bridge

volumes:
  postgres_data_prod:
